source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.2"

gem "rails", "~> 5.2.6"
gem "mysql2", ">= 0.4.4", "< 0.6.0"
gem "puma", "~> 3.11"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.2"
gem "jbuilder", "~> 2.5"
gem "bootsnap", ">= 1.1.0", require: false
gem "active_hash"

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rubocop-airbnb"
end

group :test do
  gem "rspec-rails"
  gem "simplecov"
  gem "rspec_junit_formatter"
  gem "factory_bot_rails"
  gem "rails-controller-testing"
end

group :development do
  gem "web-console", ">= 3.3.0"
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"

  # DB migration
  gem "ridgepole"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# 日本語化
gem "rails-i18n"
gem "devise-i18n"
gem "devise-i18n-views"

# ユーザー管理
gem "devise"

# Bootstrap
gem "bootstrap", "~> 4.5"
gem "jquery-rails"
gem "devise-bootstrap-views", "~> 1.0"
gem "font-awesome-sass"

# Excel
gem "rubyXL"

# ransack
gem "ransack"

#active_hash
gem "active_hash"

# kaminari
gem "kaminari"

# decorator
gem "draper"

# aws-sdk-s3
gem "aws-sdk-s3", require: false

# Select2 for rails asset pipeline
gem "select2-rails"