class Industry < ActiveHash::Base
  include ActiveHash::Enum
  self.data = [
    { id: 1, code: "M1", name: "飲食業（一般）", display_name: "M1.飲食業（一般）" },
    { id: 2, code: "M2", name: "飲食業（スナック、バー等夜間のみ営業）", display_name: "M2.飲食業（スナック、バー等夜間のみ営業）" },
    { id: 3, code: "M3", name: "飲食業（その他）", display_name: "M3.飲食業（その他）" },
    { id: 4, code: "M4", name: "宿泊業（旅館・ホテル業）", display_name: "M4.宿泊業（旅館・ホテル業）" },
    { id: 5, code: "M5", name: "民泊", display_name: "M5.民泊" },
    { id: 6, code: "I1", name: "卸売・小売業（アパレル）", display_name: "I1.卸売・小売業（アパレル）" },
    { id: 7, code: "I2", name: "卸売・小売業（食品、テイクアウト飲食含む）", display_name: "I2.卸売・小売業（食品、テイクアウト飲食含む）" },
    { id: 8, code: "I3", name: "卸売・小売業（自動車）", display_name: "I3.卸売・小売業（自動車）" },
    { id: 9, code: "I4", name: "卸売・小売業（その他）", display_name: "I4.卸売・小売業（その他）" },
    { id: 10, code: "L1", name: "士業", display_name: "L1.士業" },
    { id: 11, code: "L2", name: "広告業（イベント制作含む）", display_name: "L2.広告業（イベント制作含む）" },
    { id: 12, code: "L3", name: "コンサルティング業", display_name: "L3.コンサルティング業" },
    { id: 13, code: "L4", name: "芸能関連業（芸能事務所、劇団等）", display_name: "L4.芸能関連業（芸能事務所、劇団等）" },
    { id: 14, code: "L5", name: "専門サービス業（設計、デザイン）", display_name: "L5.専門サービス業（設計、デザイン）" },
    { id: 15, code: "L6", name: "学術研究", display_name: "L6.学術研究" },
    { id: 16, code: "G1", name: "システム開発、ソフトウェア開発、ゲーム・アプリ開発", display_name: "G1.システム開発、ソフトウェア開発、ゲーム・アプリ開発" },
    { id: 17, code: "G2", name: "ほかITサービス提供（ウェブサイト制作等）", display_name: "G2.ほかITサービス提供（ウェブサイト制作等）" },
    { id: 18, code: "G3", name: "放送、マスコミ、出版、映像制作", display_name: "G3.放送、マスコミ、出版、映像制作" },
    { id: 19, code: "D1", name: "建設業、工事業", display_name: "D1.建設業、工事業" },
    { id: 20, code: "N1", name: "美容室・理容室", display_name: "N1.美容室・理容室" },
    { id: 21, code: "N2", name: "美容サロン（エステ・脱毛等）", display_name: "N2.美容サロン（エステ・脱毛等）" },
    { id: 22, code: "N3", name: "美容サロン（まつエク、ネイル等その他）", display_name: "N3.美容サロン（まつエク、ネイル等その他）" },
    { id: 23, code: "N4", name: "コインランドリー、クリーニング業", display_name: "N4.コインランドリー、クリーニング業" },
    { id: 24, code: "N5", name: "フィットネスジム、トレーニングジム", display_name: "N5.フィットネスジム、トレーニングジム" },
    { id: 25, code: "N6", name: "娯楽業（パチンコ、雀荘等）(塾等)", display_name: "N6.娯楽業（パチンコ、雀荘等）" },
    { id: 26, code: "N7", name: "旅行業", display_name: "N7.旅行業" },
    { id: 27, code: "N8", name: "ペットサロン、トリミング", display_name: "N8.ペットサロン、トリミング" },
    { id: 28, code: "N9", name: "その他生活関連サービス業", display_name: "N9.その他生活関連サービス業" },
    { id: 29, code: "P1", name: "病院", display_name: "P1.病院" },
    { id: 30, code: "P2", name: "療術（整体など）", display_name: "P2.療術（整体など）" },
    { id: 31, code: "P3", name: "ほか医療施設", display_name: "P3.ほか医療施設" },
    { id: 32, code: "P4", name: "介護・社会福祉サービス業", display_name: "P4.介護・社会福祉サービス業" },
    { id: 33, code: "P5", name: "宿泊込み介護福祉サービス業（老人ホーム、グループホーム等）", display_name: "P5.宿泊込み介護福祉サービス業（老人ホーム、グループホーム等）" },
    { id: 34, code: "P6", name: "保育園", display_name: "P6.保育園" },
    { id: 35, code: "O1", name: "学習塾", display_name: "O1.学習塾" },
    { id: 36, code: "O2", name: "ほか習い事関連", display_name: "O2.ほか習い事関連" },
    { id: 37, code: "O3", name: "教育機関（学校、幼稚園等）", display_name: "O3.教育機関（学校、幼稚園等）" },
    { id: 38, code: "K1", name: "不動産業", display_name: "K1.不動産業" },
    { id: 39, code: "K2", name: "貸会議室、貸スペース", display_name: "K2.貸会議室、貸スペース" },
    { id: 40, code: "K3", name: "ほか物品賃貸業", display_name: "K3.ほか物品賃貸業" },
    { id: 41, code: "E1", name: "製造業", display_name: "E1.製造業" },
    { id: 42, code: "E2", name: "繊維工業", display_name: "E2.繊維工業" },
    { id: 43, code: "E3", name: "印刷関連業", display_name: "E3.印刷関連業" },
    { id: 44, code: "H1", name: "運輸業", display_name: "H1.運輸業" },
    { id: 45, code: "R1", name: "職業紹介業", display_name: "R1.職業紹介業" },
    { id: 46, code: "R2", name: "修理、整備業", display_name: "R2.修理、整備業" },
    { id: 47, code: "R3", name: "建物管理業、警備業", display_name: "R3.建物管理業、警備業" },
    { id: 48, code: "R4", name: "ほか事業サービス業（コールセンター、廃棄物処理）", display_name: "R4.ほか事業サービス業（コールセンター、廃棄物処理）" },
    { id: 49, code: "R5", name: "政治・経済・文化団体・宗教", display_name: "R5.政治・経済・文化団体・宗教" },
    { id: 50, code: "J1", name: "金融業", display_name: "J1.金融業" },
    { id: 51, code: "J2", name: "保険業", display_name: "J2.保険業" },
    { id: 52, code: "F1", name: "電気・ガス・熱供給・水道業", display_name: "F1.電気・ガス・熱供給・水道業" },
    { id: 53, code: "T", name: "その他", display_name: "T.その他" },
  ]
  enum_accessor :code
end
